"""Loads the committed ``data/*.json`` into frozen records.

The JSON is the runtime source of truth, generated by ``scripts.build_data``.
Pure stdlib -- no workbook, no tkinter. ``load_game_data`` validates structure
and counts so the app fails loudly if the data ever drifts from the workbook.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

__all__ = [
    "StatRange",
    "Ore",
    "Weapon",
    "Race",
    "Rune",
    "Achievement",
    "GameData",
    "load_game_data",
    "DEFAULT_DATA_DIR",
    "EXPECTED_COUNTS",
]

# Counts from the source workbook; loading rejects data/ that drifted.
EXPECTED_COUNTS = {
    "ores": 140,
    "weapons": 79,
    "races": 16,
    "runes": 47,
    "achievements": 16,
}

SELECT_ORE = "Select Ore"
NONE_LABEL = "None"


@dataclass(frozen=True)
class StatRange:
    """Share-scaling range for one ore stat.

    ``base`` applies at 10% share and ramps linearly to ``max`` at 30% -- the
    workbook's ``(base+(max-base)*MIN((share-0.1)/0.2,1))`` term.  ``divisor``
    is 100 for percent stats, 1 for fire/poison durations.
    """

    base: float
    max: float
    divisor: int


@dataclass(frozen=True)
class Ore:
    name: str
    multiplier: float
    equipment: str | None
    trait10: str | None
    trait30: str | None
    comments: str | None
    stats: Mapping[str, StatRange]

    @property
    def is_weapon(self) -> bool:
        """C14's ``ISNUMBER(SEARCH("eapon", equipment))`` test (case-insensitive)."""
        return bool(self.equipment) and "eapon" in self.equipment.lower()

    def stat(self, name: str) -> StatRange | None:
        return self.stats.get(name)


@dataclass(frozen=True)
class Weapon:
    name: str
    type: str
    interval: float
    damage: float


@dataclass(frozen=True)
class Race:
    name: str
    default_trait: str | None
    available_traits: tuple[str, ...]


@dataclass(frozen=True)
class Rune:
    name: str
    stat: str | None
    value: float | None


@dataclass(frozen=True)
class Achievement:
    name: str
    stat: str | None
    value: float | None


@dataclass(frozen=True)
class GameData:
    ores: tuple[Ore, ...]
    weapons: tuple[Weapon, ...]
    races: tuple[Race, ...]
    runes: tuple[Rune, ...]
    achievements: tuple[Achievement, ...]
    weapon_types: tuple[str, ...]
    race_bonus_types: tuple[str, ...]
    select_ore: str = SELECT_ORE
    none_label: str = NONE_LABEL

    _ore_index: Mapping[str, Ore] = field(init=False, repr=False)
    _weapon_index: Mapping[str, Weapon] = field(init=False, repr=False)
    _race_index: Mapping[str, Race] = field(init=False, repr=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "_ore_index", {o.name: o for o in self.ores})
        object.__setattr__(self, "_weapon_index", {w.name: w for w in self.weapons})
        object.__setattr__(self, "_race_index", {r.name: r for r in self.races})

    def ore(self, name: str) -> Ore | None:
        return self._ore_index.get(name)

    def weapon(self, name: str) -> Weapon | None:
        return self._weapon_index.get(name)

    def race(self, name: str) -> Race | None:
        return self._race_index.get(name)

    def weapons_by_type(self, wtype: str) -> tuple[Weapon, ...]:
        return tuple(w for w in self.weapons if w.type == wtype)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_game_data(data_dir: str | Path | None = None) -> GameData:
    """Load and validate the committed ``data/*.json`` files.

    Raises ``ValueError`` on a missing file, drifted counts, or a malformed
    record.
    """
    base = Path(data_dir) if data_dir is not None else DEFAULT_DATA_DIR
    raw_ores = _load_json(base / "ores.json")
    raw_weapons = _load_json(base / "weapons.json")
    raw_races = _load_json(base / "races.json")
    raw_runes = _load_json(base / "runes.json")
    raw_achievements = _load_json(base / "achievements.json")

    ores = tuple(_build_ore(o) for o in raw_ores["ores"])
    weapons = tuple(
        Weapon(
            name=w["name"],
            type=w["type"],
            interval=float(w["interval"]),
            damage=float(w["damage"]),
        )
        for w in raw_weapons["weapons"]
    )
    races = tuple(
        Race(
            name=r["name"],
            default_trait=r.get("default_trait"),
            available_traits=tuple(r.get("available_traits") or ()),
        )
        for r in raw_races["races"]
    )
    runes = tuple(
        Rune(name=r["name"], stat=r.get("stat"), value=r.get("value"))
        for r in raw_runes["runes"]
    )
    achievements = tuple(
        Achievement(name=a["name"], stat=a.get("stat"), value=a.get("value"))
        for a in raw_achievements["achievements"]
    )

    data = GameData(
        ores=ores,
        weapons=weapons,
        races=races,
        runes=runes,
        achievements=achievements,
        weapon_types=tuple(raw_weapons["types"]),
        race_bonus_types=tuple(raw_weapons["race_bonus_types"]),
        select_ore=raw_ores.get("select_ore", SELECT_ORE),
        none_label=raw_runes.get("none", NONE_LABEL),
    )

    _validate(data)
    return data


def _build_ore(raw: dict) -> Ore:
    stats: dict[str, StatRange] = {}
    for stat, rng in (raw.get("stats") or {}).items():
        if set(rng) != {"base", "max", "divisor"}:
            raise ValueError(f"ore {raw['name']!r}: malformed stat range {rng!r}")
        stats[stat] = StatRange(
            base=float(rng["base"]),
            max=float(rng["max"]),
            divisor=int(rng["divisor"]),
        )
    multiplier = raw.get("multiplier")
    if multiplier is None:
        raise ValueError(f"ore {raw['name']!r}: missing multiplier")
    return Ore(
        name=raw["name"],
        multiplier=float(multiplier),
        equipment=raw.get("equipment"),
        trait10=raw.get("trait10"),
        trait30=raw.get("trait30"),
        comments=raw.get("comments"),
        stats=stats,
    )


def _validate(data: GameData) -> None:
    counts = {
        "ores": len(data.ores),
        "weapons": len(data.weapons),
        "races": len(data.races),
        "runes": len(data.runes),
        "achievements": len(data.achievements),
    }
    drift = {
        key: (expected, counts[key])
        for key, expected in EXPECTED_COUNTS.items()
        if counts[key] != expected
    }
    if drift:
        raise ValueError(f"data/ drifted from workbook extraction: {drift}")

    names = [o.name for o in data.ores]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise ValueError(f"duplicate ore names in data/: {sorted(dupes)}")

    if not data.weapon_types:
        raise ValueError("weapons.json: empty weapon type list (C12)")
    if not data.race_bonus_types:
        raise ValueError("weapons.json: empty race-bonus type list (C23)")


DEFAULT_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
